M48
; DRILL file {KiCad (7.0.0)} date Thu Mar  9 18:44:14 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-03-09T18:44:14+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
%
G90
G05
T1
X103.0Y-65.0
X103.0Y-105.0
X167.0Y-65.0
X167.0Y-105.0
T0
M30
